
language: go

go:
  - "1.x"
  - "1.13"
  - "1.16.x"
  - tip
  - master

before_install:
  - go get -t -v ./...

install:
  - go get -v github.com/stretchr/testify

script:
  # - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  include:
    # Master channel.
    # All *nix releases are done on the Master channel to take advantage
    # of the regex library's multiple pattern SIMD search.
    - os: linux
      go: master
    - os: osx
      go: master

notifications:
  email:
    on_success: never
