
language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
  - glide install

matrix:
  fast_finish: true
  include:
    # Master channel.
    # All *nix releases are done on the Master channel to take advantage
    # of the regex library's multiple pattern SIMD search.
    - os: linux
      go: master
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      go: master
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      go: master
      # XML_CATALOG_FILES is apparently necessary for asciidoc on macOS.
      env: TARGET=x86_64-apple-darwin XML_CATALOG_FILES=/usr/local/etc/xml/catalog
    - os: linux
      go: master
      env: TARGET=arm-unknown-linux-gnueabihf GCC_VERSION=4.8
      addons:
        apt:
          packages:
          - gcc-4.8-arm-linux-gnueabihf
          - binutils-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
          # For generating man page.
          - libxslt1-dev
          - asciidoc
          - docbook-xsl
          - xsltproc
          - libxml2-utils
    # Minimum Rust supported channel. We enable these to make sure ripgrep
    # continues to work on the advertised minimum Rust version.
    - os: linux
      go: 1.8
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      go: 1.8
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      go: 1.8
      env: TARGET=arm-unknown-linux-gnueabihf GCC_VERSION=4.8
      addons:
        apt:
          packages:
          - gcc-4.8-arm-linux-gnueabihf
          - binutils-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
          # For generating man page.
          - libxslt1-dev
          - asciidoc
          - docbook-xsl
          - xsltproc
          - libxml2-utils
notifications:
  email:
    on_success: never
