
language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

install:
  - go get -v github.com/stretchr/testify

matrix:
  fast_finish: true
  include:
    # Master channel.
    # All *nix releases are done on the Master channel to take advantage
    # of the regex library's multiple pattern SIMD search.
    - os: linux
      go: master
    - os: osx
      go: master

notifications:
  email:
    on_success: never
